<div class="footer">
    <div class="footer_bg"></div>
    <div class="ft_box">
        <dl class="ft_con">
            <dt>Copyright © 2015 比特e学堂. All Rights Reserved.浙ICP备16044533号</dt>
            <dd><a href="JavaScript:void(0)">关于我们</a></dd>
            <dd><a href="JavaScript:void(0)">法律声明</a></dd>
        </dl>
    </div>
    <div style="width:300px;margin:0 auto; padding:20px 0;">
        <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010802003761" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="__PUBLIC__/Home/images/gongan.jpg" style="float:left;width:20px;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">浙公网安备 33010802003761号</p></a>
    </div>
</div>