<div class="footer2">
  <div class="top">
      <span>比特e学堂，比特ABC，比特英语</span>
      <span>杭州幼儿英语在线培训|杭州在线英语学习|外教一对一</span>
      <span>-</span>
      <span>比特ABC</span>
  </div>
  <div class="main">
    <div class="container">
      <div class="main-top clearfix">
        <span class="fn-left">销售热线：135.1569558</span>
        <span class="fn-right">中国.浙江.杭州</span>
      </div>
      <div class="main-link">
        <p><img src="./images/footer2/tel.png" alt="" >13501569558</p>
        <p><img src="./images/footer2/web.png" alt="" >http://hangzhou.biteabc.com/</p>
      </div>
      <div class="main-copyright">
        <p>版权所有：比特英语杭州区</p>
        <p>为您提供专业的杭州幼儿英语在线培训，杭州英语外教在线试听</p>
      </div>
    </div>
    <div class="line"></div>
    <div class="main-friends">
      合作伙伴<img src="./images/footer2/brands.jpg" alt="">
    </div>
  </div>
  <div class="bottom">
    <p>杭州外教一对一在线培训 | 上海外教一对一在线培训 | 北京外教一对一在线培训 | 成都外教一对一在线培训</p>
    <p>深圳外教一对一在线培训 | 广州外教一对一在线培训 | 长沙外教一对一在线培训</p>
  </div>
</div>