<!-- 百度以及360统计 -->
<script type="text/javascript" src="//s.union.360.cn/68810.js"></script>
<script>
    // var _hmt = _hmt || [];
    // (function() {
    //   var hm = document.createElement("script");
    //   hm.src = "https://hm.baidu.com/hm.js?a9c642951a41e54dc9bbc4bdab3a9050";
    //   var s = document.getElementsByTagName("script")[0]; 
    //   s.parentNode.insertBefore(hm, s);
    // })();

    // 百度统计
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "//hm.baidu.com/hm.js?70de8aa469c8bf9232e36fff18dd5227";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>

<!--[if lt IE 9]>
<script type="text/javascript" src="__PUBLIC__/Home/pie.js"> </script>
<script type="text/javascript">
    $(function(){
        if (window.PIE) {
            $('.rounded').forEach(function () {
                PIE.attach(this);
            });
        }
    })
</script>
<![endif]-->

<script src="js/common.js"></script>