<header class="header clearfix">
    <div class="logo fn-left">
        <a href="http://m.biteabc.com"><img src="./images/logo.png"></a>
    </div>
    <div class="header-btn fn-right">
        
        <!-- <notempty name="_SESSION['student']"> -->
            <a href="http://www.biteabc.com/Student/"><img src="./images/people.png"></a>  
      <!--   <else />
            <a href="__APP__/register/"><img src="./images/people.png"></a> 
        </notempty> -->
        
        <a href="tel:057185333505"><img src="./images/phone.png"></a>
    </div>
</header>