<div class="joinus container">
  <img src="./images/joinus/joinus_1.jpg" alt="" class="join-us">
  <div class="join-1">
    <p>想让孩子从小说一口地道流利的英语吗？</p>
    <p>想让英语学习成为孩子最开心最愉悦的休闲方式吗？想让孩子体验最高效最科学的教学内容和课堂方式吗？</p>
    <p>给Bite半小时，这些我们全部能做到！</p>
  </div>
  <div class="join-2">
    <p class="orange">加入Bite，我们一起唱歌，一起学习</p>
    <p class="orange">一起Bite ABC......</p>
  </div>
  <a href="#" class="join-btn">立即报名，免费预约测评</a>
  <img src="./images/joinus/joinus_2.jpg" alt="" class="join-bg">
</div>